// Generated by uniffi-bindgen-react-native
#include "rn-csca.h"
#include "generated/csca_parser.hpp"

namespace rncsca {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeCscaParser::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}