// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "lukachi-rn-csca.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RnCscaSpec.h"

@interface RnCsca : NSObject <NativeRnCscaSpec>
#else
#import <React/RCTBridgeModule.h>

@interface RnCsca : NSObject <RCTBridgeModule>
#endif

@end